# 로그인 시뮬레이션 (유저 정보로 직접 로그인)
POST http://localhost:8080/login
Content-Type: application/json

{
  "loginId": "1234",
  "password": "1234"
}

#### 게시글 생성 요청
POST http://localhost:8080/boards
Content-Type: application/json

{
"title": "New Board",
"content": "Content of the new board"
}

##### 생성된 게시글 확인
GET http://localhost:8080/boards

######게시글 삭제 요청
DELETE http://localhost:8080/boards/1
