####Create board
POST http://localhost:8080/boards
Content-Type: application/json

{
  "title": "First Board",
  "content": "This is the content of the first board."
}

#####PUT test
PUT http://localhost:8080/boards/1
Content-Type: application/json

{
"title": "Updated Board Title",
"content": "This is the updated content of the board."
}

########Get all boards
GET http://localhost:8080/boards

########Get board by id
GET http://localhost:8080/boards/1

########Delete board
DELETE http://localhost:8080/boards/1

